name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - run: java -version
      - run: mvn --batch-mode --update-snapshots verify
      - run: echo "Begin BuildÔºÅ"
      - run: mvn compile
      - run: echo "Build End !"
      - run: mvn test
      - run: echo "Test Success!"