name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: java -version
      - run: echo "Begin Buildï¼"
      - run: mvn compile
      - run: echo "Build End !"
      - run: mvn test
      - run: echo "Test Success!"