name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: java -version
      - run: mvn -B package --file testAction/pom.xml
      - run: echo "Begin BuildÔºÅ"
      - run: mvn compile
      - run: echo "Build End !"
      - run: mvn test
      - run: echo "Test Success!"